export const defaultContacts = [
    {
        id: "c1",
        name: "Sophie Martin",
        email: "sophie.martin@techcorp.fr",
        company: "TechCorp",
        avatar: "SM",
        status: "active",
        lastActivity: "Il y a 2 heures",
        phone: "+33 6 12 34 56 78",
    },
    {
        id: "c2",
        name: "Lucas Bernard",
        email: "lucas.b@innovate.io",
        company: "Innovate.io",
        avatar: "LB",
        status: "lead",
        lastActivity: "Il y a 5 heures",
        phone: "+33 6 98 76 54 32",
    },
    {
        id: "c3",
        name: "Emma Dubois",
        email: "emma.dubois@startup.co",
        company: "StartupCo",
        avatar: "ED",
        status: "active",
        lastActivity: "Hier",
        phone: "+33 7 11 22 33 44",
    },
    {
        id: "c4",
        name: "Thomas Petit",
        email: "t.petit@bigfirm.com",
        company: "BigFirm",
        avatar: "TP",
        status: "inactive",
        lastActivity: "Il y a 3 jours",
        phone: "+33 6 55 66 77 88",
    },
    {
        id: "c5",
        name: "Julie Moreau",
        email: "julie@designlab.fr",
        company: "DesignLab",
        avatar: "JM",
        status: "active",
        lastActivity: "Il y a 30 min",
        phone: "+33 7 99 88 77 66",
    },
    {
        id: "c6",
        name: "Antoine Leroy",
        email: "a.leroy@mediagroup.fr",
        company: "MediaGroup",
        avatar: "AL",
        status: "lead",
        lastActivity: "Il y a 1 heure",
        phone: "+33 6 44 33 22 11",
    },
];
export const defaultTickets = [
    {
        id: "t1",
        title: "Bug d'affichage sur la page de paiement",
        description: "Le bouton de validation ne s'affiche pas correctement sur mobile",
        status: "open",
        priority: "high",
        assignee: "Marie L.",
        contact: "Sophie Martin",
        createdAt: "2026-01-28",
        updatedAt: "2026-01-28",
    },
    {
        id: "t2",
        title: "Demande d'export CSV",
        description: "Le client souhaite exporter ses donnees au format CSV",
        status: "in-progress",
        priority: "medium",
        assignee: "Paul R.",
        contact: "Lucas Bernard",
        createdAt: "2026-01-27",
        updatedAt: "2026-01-28",
    },
    {
        id: "t3",
        title: "Probleme de connexion API",
        description: "L'integration avec le service tiers ne fonctionne plus",
        status: "open",
        priority: "urgent",
        assignee: "Marie L.",
        contact: "Emma Dubois",
        createdAt: "2026-01-28",
        updatedAt: "2026-01-28",
    },
    {
        id: "t4",
        title: "Mise a jour documentation",
        description: "Mettre a jour la documentation utilisateur",
        status: "resolved",
        priority: "low",
        assignee: "Jean D.",
        contact: "Thomas Petit",
        createdAt: "2026-01-25",
        updatedAt: "2026-01-27",
    },
    {
        id: "t5",
        title: "Amelioration performance dashboard",
        description: "Le dashboard met plus de 5 secondes a charger pour les gros comptes",
        status: "in-progress",
        priority: "high",
        assignee: "Paul R.",
        contact: "Julie Moreau",
        createdAt: "2026-01-26",
        updatedAt: "2026-01-28",
    },
    {
        id: "t6",
        title: "Demande nouvelle fonctionnalite",
        description: "Integration avec Slack pour les notifications",
        status: "open",
        priority: "medium",
        assignee: "Jean D.",
        contact: "Antoine Leroy",
        createdAt: "2026-01-28",
        updatedAt: "2026-01-28",
    },
];
export const defaultConversations = [
    {
        id: "conv1",
        contactName: "Sophie Martin",
        contactAvatar: "SM",
        lastMessage: "Merci pour votre aide, c'est parfait !",
        timestamp: "14:32",
        unread: 0,
        channel: "chat",
        messages: [
            {
                id: "m1",
                content: "Bonjour, j'ai un souci avec ma commande #4521",
                sender: "contact",
                timestamp: "14:20",
            },
            {
                id: "m2",
                content: "Bonjour Sophie ! Je vais verifier cela immediatement pour vous.",
                sender: "agent",
                timestamp: "14:22",
            },
            {
                id: "m3",
                content: "J'ai detecte que la commande #4521 est bloquee en raison d'une erreur d'adresse. Je suggere de contacter le client pour confirmer.",
                sender: "ai",
                timestamp: "14:23",
            },
            {
                id: "m4",
                content: "Nous avons identifie le probleme. Pouvez-vous confirmer votre adresse de livraison ?",
                sender: "agent",
                timestamp: "14:25",
            },
            {
                id: "m5",
                content: "Oui bien sur, c'est 12 rue de la Paix, 75002 Paris",
                sender: "contact",
                timestamp: "14:28",
            },
            {
                id: "m6",
                content: "Merci pour votre aide, c'est parfait !",
                sender: "contact",
                timestamp: "14:32",
            },
        ],
    },
    {
        id: "conv2",
        contactName: "Lucas Bernard",
        contactAvatar: "LB",
        lastMessage: "Est-ce que l'API sera disponible bientot ?",
        timestamp: "13:15",
        unread: 2,
        channel: "email",
        messages: [
            {
                id: "m7",
                content: "Bonjour, je souhaite savoir quand la nouvelle API sera disponible.",
                sender: "contact",
                timestamp: "13:00",
            },
            {
                id: "m8",
                content: "D'apres notre roadmap, l'API v2 est prevue pour la semaine prochaine.",
                sender: "ai",
                timestamp: "13:01",
            },
            {
                id: "m9",
                content: "Est-ce que l'API sera disponible bientot ?",
                sender: "contact",
                timestamp: "13:15",
            },
        ],
    },
    {
        id: "conv3",
        contactName: "Emma Dubois",
        contactAvatar: "ED",
        lastMessage: "Je vous envoie les specs par email",
        timestamp: "12:45",
        unread: 1,
        channel: "whatsapp",
        messages: [
            {
                id: "m10",
                content: "Hello ! Avez-vous recu les specifications du projet ?",
                sender: "contact",
                timestamp: "12:30",
            },
            {
                id: "m11",
                content: "Pas encore, mais nous les attendons avec impatience !",
                sender: "agent",
                timestamp: "12:35",
            },
            {
                id: "m12",
                content: "Je vous envoie les specs par email",
                sender: "contact",
                timestamp: "12:45",
            },
        ],
    },
    {
        id: "conv4",
        contactName: "Julie Moreau",
        contactAvatar: "JM",
        lastMessage: "Le design est valide, on peut lancer !",
        timestamp: "11:20",
        unread: 0,
        channel: "chat",
        messages: [
            {
                id: "m13",
                content: "Les maquettes sont pretes pour validation",
                sender: "contact",
                timestamp: "11:00",
            },
            {
                id: "m14",
                content: "Super ! Laissez-moi les examiner.",
                sender: "agent",
                timestamp: "11:10",
            },
            {
                id: "m15",
                content: "Le design est valide, on peut lancer !",
                sender: "contact",
                timestamp: "11:20",
            },
        ],
    },
    {
        id: "conv5",
        contactName: "Antoine Leroy",
        contactAvatar: "AL",
        lastMessage: "On planifie un call demain ?",
        timestamp: "10:05",
        unread: 3,
        channel: "chat",
        messages: [
            {
                id: "m16",
                content: "J'aimerais discuter de l'integration Slack pour notre equipe",
                sender: "contact",
                timestamp: "09:50",
            },
            {
                id: "m17",
                content: "Bien sur, nous pouvons planifier un appel.",
                sender: "agent",
                timestamp: "09:55",
            },
            {
                id: "m18",
                content: "On planifie un call demain ?",
                sender: "contact",
                timestamp: "10:05",
            },
        ],
    },
];
export const defaultCampaigns = [
    {
        id: "camp1",
        name: "Lancement Produit V2",
        status: "active",
        type: "email",
        sent: 12450,
        opened: 4320,
        clicked: 1856,
        startDate: "2026-01-15",
        endDate: "2026-02-15",
    },
    {
        id: "camp2",
        name: "Promo Nouvel An",
        status: "completed",
        type: "email",
        sent: 8900,
        opened: 3560,
        clicked: 1245,
        startDate: "2025-12-26",
        endDate: "2026-01-05",
    },
    {
        id: "camp3",
        name: "Onboarding Automatique",
        status: "active",
        type: "email",
        sent: 2340,
        opened: 1870,
        clicked: 980,
        startDate: "2026-01-01",
        endDate: "2026-03-01",
    },
    {
        id: "camp4",
        name: "Re-engagement Clients",
        status: "draft",
        type: "sms",
        sent: 0,
        opened: 0,
        clicked: 0,
        startDate: "2026-02-01",
        endDate: "2026-02-28",
    },
    {
        id: "camp5",
        name: "Notification Mise a Jour",
        status: "paused",
        type: "push",
        sent: 5600,
        opened: 3920,
        clicked: 1120,
        startDate: "2026-01-20",
        endDate: "2026-01-30",
    },
];
export const dashboardStats = {
    totalContacts: 2847,
    activeTickets: 42,
    openConversations: 18,
    campaignsSent: 29290,
    contactsGrowth: 12.5,
    ticketsResolved: 156,
    avgResponseTime: "2.4 min",
    satisfactionRate: 94.2,
};
export const revenueData = [
    { month: "Juil", revenue: 18500, target: 20000 },
    { month: "Aout", revenue: 22300, target: 21000 },
    { month: "Sep", revenue: 19800, target: 22000 },
    { month: "Oct", revenue: 25600, target: 23000 },
    { month: "Nov", revenue: 28900, target: 25000 },
    { month: "Dec", revenue: 32100, target: 27000 },
    { month: "Jan", revenue: 35400, target: 30000 },
];
export const ticketsByCategory = [
    { name: "Support", value: 35, fill: "#3590E3" },
    { name: "Bug", value: 25, fill: "#EF4444" },
    { name: "Feature", value: 20, fill: "#BAF09D" },
    { name: "Question", value: 15, fill: "#F59E0B" },
    { name: "Autre", value: 5, fill: "#6366F1" },
];
export const weeklyActivity = [
    { day: "Lun", conversations: 45, tickets: 12, emails: 34 },
    { day: "Mar", conversations: 52, tickets: 18, emails: 41 },
    { day: "Mer", conversations: 38, tickets: 15, emails: 28 },
    { day: "Jeu", conversations: 61, tickets: 22, emails: 45 },
    { day: "Ven", conversations: 55, tickets: 19, emails: 39 },
    { day: "Sam", conversations: 18, tickets: 5, emails: 12 },
    { day: "Dim", conversations: 8, tickets: 2, emails: 5 },
];
export const recentActivities = [
    {
        id: "a1",
        type: "ticket",
        message: 'Nouveau ticket cree: "Bug page de paiement"',
        time: "Il y a 5 min",
        user: "Sophie Martin",
    },
    {
        id: "a2",
        type: "conversation",
        message: "Nouvelle conversation demarree avec Lucas Bernard",
        time: "Il y a 15 min",
        user: "Lucas Bernard",
    },
    {
        id: "a3",
        type: "campaign",
        message: 'Campagne "Lancement V2" envoyee a 12,450 contacts',
        time: "Il y a 1 heure",
        user: "Systeme",
    },
    {
        id: "a4",
        type: "contact",
        message: "Nouveau lead ajoute: Antoine Leroy",
        time: "Il y a 2 heures",
        user: "Auto",
    },
    {
        id: "a5",
        type: "ticket",
        message: 'Ticket "Export CSV" resolu par Paul R.',
        time: "Il y a 3 heures",
        user: "Paul R.",
    },
];
